services:
  wukong:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WUKONG_ADMIN_PASSWORD=bruh
      - REDIS_URL=redis://127.0.0.1:6379