// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameStartedMessage } from "./GameStartedMessage";
import type { HaltTimer } from "./HaltTimer";
import type { TeamDraftMessage } from "./TeamDraftMessage";
import type { TurnTimer } from "./TurnTimer";

export type GameMessage = { "type": "PlayerJoined", username: string, player_id: string, } | { "type": "PlayerLeft", username: string, player_id: string, } | { "type": "PlayerDisconnected", username: string, player_id: string, } | { "type": "GameStarted" } & GameStartedMessage | { "type": "ChatMessage", username: string, message: string, } | { "type": "HaltTimer" } & HaltTimer | { "type": "TurnTimer" } & TurnTimer | { "type": "TeamDraft" } & TeamDraftMessage;
