// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NextRound = { yapper_id: string, yapper_index: number, round: number, team_size: number, };
