// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Round = { round: number, pool: string, competition: string, team_size: number, starting_drafter_id: string, current_drafter_id: string, player_to_picks: { [key in string]?: Array<string> }, };
