// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AwardPoint } from "./AwardPoint";
import type { AwardingPhase } from "./AwardingPhase";
import type { CompleteGame } from "./CompleteGame";
import type { DraftPick } from "./DraftPick";
import type { NextRound } from "./NextRound";
import type { SetCompetitionMessage } from "./SetCompetitionMessage";
import type { SetPoolMessage } from "./SetPoolMessage";
import type { StartDraft } from "./StartDraft";

export type TeamDraftMessage = { "msg_type": "SetPool" } & SetPoolMessage | { "msg_type": "SetCompetition" } & SetCompetitionMessage | { "msg_type": "StartDraft" } & StartDraft | { "msg_type": "DraftPick" } & DraftPick | { "msg_type": "AwardingPhase" } & AwardingPhase | { "msg_type": "AwardPoint" } & AwardPoint | { "msg_type": "NextRound" } & NextRound | { "msg_type": "CompleteGame" } & CompleteGame;
