// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamDraftMessage = { "msg_type": "SetPool", pool: string, } | { "msg_type": "SetCompetition", competition: string, };
