// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameMessage } from "./GameMessage";
import type { TimerReason } from "./TimerReason";

export type ActionTimer = { duration_seconds: bigint, action_key: string, default_action: GameMessage, reason: TimerReason, };
