// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameMode } from "./GameMode";
import type { TeamDraftState } from "./TeamDraftState";

export type GameStartedMessage = { game_type: GameMode, initial_team_draft_state: TeamDraftState | null, };
