// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";
import type { TeamDraftManager } from "./TeamDraftManager";

export type Game = { id: string, code: string, host_id: string, players: Array<Player>, max_players: number, created_at: number, team_draft: TeamDraftManager, };
