// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerReason } from "./TimerReason";

export type HaltTimer = { end_timestamp_ms: bigint, reason: TimerReason, };
