// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LobbyMessage = { "type": "PlayerJoined", username: string, player_id: string, } | { "type": "PlayerLeft", username: string, player_id: string, } | { "type": "GameStarted", game_type: string, } | { "type": "ChatMessage", username: string, message: string, };
