// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Round = { pool: string, competition: string, team_size: number, player_to_picks: { [key in string]?: Array<string> }, };
