// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Round } from "./Round";
import type { TeamDraftPhase } from "./TeamDraftPhase";

export type TeamDraftState = { yapper_id: string, yapper_index: number, max_rounds: number, phase: TeamDraftPhase, round_data: Round, player_points: { [key in string]?: number }, };
