// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamDraftTimerReason } from "./TeamDraftTimerReason";

export type TimerReason = { "TeamDraft": TeamDraftTimerReason };
